server:
   port: 8080
   servlet:
      context-path: /
debug:
    true      

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://${URL_BANCO:localhost}:${PORTA_BANCO:5432}/${NOME_BANCO:cdt} 
        username: ${USUARIO_BANCO:postgres}
        password: ${SENHA_BANCO:postgres}
        hikari.minimumIdle: 3
        hikari.maximumPoolSize: 5
        hikari.idleTimeout: 30000
        hikari.poolName: SpringBootJPAHikariCP
        hikari.maxLifetime: 2000000
        hikari.connectionTimeout: 30000
    jpa.show-sql : true
    jpa.hibernate.ddl-auto : update
    jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
  
springfox.documentation.swagger.v2.path: /docs
logging:
    level: 
       org.springframework: ERROR
    
elk:
    ip : 0
    porta : 0